/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssemblyPcRouteImport } from './routes/assembly-pc'
import { Route as ListPcRouteImport } from './routes/list-pc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyPcRoute = AssemblyPcRouteImport.update({
  id: '/assembly-pc',
  path: '/assembly-pc',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPcRoute = ListPcRouteImport.update({
  id: '/list-pc',
  path: '/list-pc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assembly-pc': typeof AssemblyPcRoute
  '/list-pc': typeof ListPcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assembly-pc': typeof AssemblyPcRoute
  '/list-pc': typeof ListPcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assembly-pc': typeof AssemblyPcRoute
  '/list-pc': typeof ListPcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assembly-pc' | '/list-pc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assembly-pc' | '/list-pc'
  id: '__root__' | '/' | '/assembly-pc' | '/list-pc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssemblyPcRoute: typeof AssemblyPcRoute
  ListPcRoute: typeof ListPcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-pc': {
      id: '/assembly-pc'
      path: '/assembly-pc'
      fullPath: '/assembly-pc'
      preLoaderRoute: typeof AssemblyPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-pc': {
      id: '/list-pc'
      path: '/list-pc'
      fullPath: '/list-pc'
      preLoaderRoute: typeof ListPcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssemblyPcRoute: AssemblyPcRoute,
  ListPcRoute: ListPcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
